# @package _global_

defaults:
    - override /module/regression_model: utae
    - override /module/super_resolution_model: null

project: "train_sera"
run_name: h-utae_as
run_version: v1_${run_name}
data_dir: data
ckpt_path: last

module:
    instance:
        super_resolution_model: null
    metrics:
        forest_mask_path: ${data_dir}/open_canopy/forest_mask.parquet
        classification_path: ${data_dir}/open_canopy/

datamodule:
    instance:
        batch_size: 8
        
    dataset:
        patch_size_input: 32
        patch_size_target: 128
        resolution_input: 2.5
        patch_size_input: 128
        get_targets:
            targets_path: ${data_dir}/open_canopy/

